const dictionary = {
  "Checking backend": "检查后端连接",
  Connecting: "正在连接",
  "Backend connected": "后端已连接",
  "Fallback mode": "本地兜底模式",

  empty: "空闲",
  occupied: "已停放",
  charging: "充电中",
  buffer: "周转区",
  maintenance: "维护中",
  Shallow: "浅层区",
  Mid: "中层区",
  Deep: "深层区",

  PARKED: "停车中",
  RETRIEVING: "取车中",
  TOUCHING: "临停取物",
  PAYING: "待支付",
  FINISHED: "已完成",
  ABNORMAL: "异常复核",
  IDLE: "待命",
  CARRYING: "搬运中",
  TRANSIT: "行驶中",
  CHARGING: "充电中",
  ONLINE: "在线",
  OPEN: "开启",
  CLOSED: "关闭",
  READY: "就绪",
  LOCKDOWN: "锁定",
  PREPARE_OPEN: "准备放行",
  Charging: "充电中",
  Available: "可用",
  Preparing: "准备中",
  Finishing: "即将结束",
  Accepted: "已授权",
  Authorizing: "授权中",
  Idle: "空闲",

  Safety: "安全",
  Device: "设备",
  Order: "订单",
  Gate: "闸机",
  Charging: "充电中",
  Vision: "视觉",
  Billing: "计费",
  Dispatch: "调度",
  High: "高",
  Medium: "中",
  Low: "低",
  info: "信息",
  low: "低",
  medium: "中",
  high: "高",
  critical: "严重",
  stable: "稳定",
  warning: "预警",

  "Vehicle entry": "车辆入场",
  "Retrieve request": "取车请求",
  "Touch-and-go": "临停取物",
  "Pending payment": "待支付",
  "Completed exit": "完成离场",
  "Exception review": "异常复核",
  "Active parking": "停车中",
  Dispatching: "调度中",
  "At handoff bay": "交接区等待",
  "Awaiting payment": "等待支付",
  Closed: "已关闭",
  "Needs review": "需要复核",

  "Standard retrieval": "标准取车",
  "Charging bay release": "充电车位放行",
  "Reserved outbound": "预约出场",
  "Pre-dispatch relocation": "高峰预调度移位",
  "VIP retrieval": "VIP 优先取车",
  "Charging connector release": "充电枪释放",
  "Payment confirmation hold": "支付确认等待",
  "Manual review transfer": "人工复核转运",
  "Night package outbound": "夜间套餐出场",
  "Inbound storage": "入场存车",
  FIFO: "先到先取",
  "Charging done": "充电完成",
  Touch: "临取",
  Booking: "预约",
  PRE: "预调度",
  VIP: "VIP",
  EV: "新能源",
  PAY: "支付",
  RISK: "风控",
  Night: "夜间",
  IN: "入场",

  patrol: "巡检",
  deliver: "送车",
  relocate: "移位",
  dock: "回桩",
  store: "存车",
  retrieve: "取车",
  handoff: "交接",
  navigate: "导航",
  hold: "保持",
  "vip-priority": "VIP 优先",

  ACCESS_GRANTED: "准入通过",
  MAINTENANCE_READY: "维护就绪",
  ESTOP_ACTIVE: "急停生效",
  ESTOP_RELEASED: "急停解除",
  RECOVERY_READY: "恢复就绪",
  OCR_OK: "车牌校验通过",
  VIP_RELEASE: "VIP 放行",
  QUEUE_RELEASE: "队列放行",
  EXIT_CONFIRMED: "离场确认",
  QUEUE_BUILDUP: "排队积压",
  RELEASE_READY: "放行就绪",
  PLATE_READ: "车牌识别",
  LOOP_OCCUPIED: "地感占用",
  ENERGY_DELIVERY: "充电计量",
  TASK_ASSIGNED: "任务分配",
  ROI_CLEAR: "安全区清空",
  BATTERY_LOW: "电量偏低",
  AUTHORIZE_START: "启动授权",
  SECONDARY_READ: "二次识别",
  VIP_INSERT: "VIP 插队",
  MANUAL_REVIEW: "人工复核",
  SESSION_UPDATE: "充电更新",
  RELOCATE_START: "移位开始",
  PERSON_DETECTED: "人员识别",
  SERVICE_READY: "服务通道就绪",
  TASK_QUEUED: "任务入队",
  SETTLEMENT_PENDING: "结算待确认",
  HEARTBEAT: "心跳",
  BITRATE_DIP: "码率波动",
  PATROL_TICK: "巡检完成",
  LOCK_RETRY: "锁止重试",
  HOLD_ACTIVE: "保持拦截",
  INTRUSION_DETECTED: "入侵告警",
  ORDER_CREATED: "订单创建",
  ORDER_SYNC: "订单同步",
  ALARM: "告警",
  LOCK: "锁定",
  DEGRADED: "降级",

  "Workday hourly": "工作日阶梯计费",
  "Night package": "夜间包时",
  "EV charging": "新能源充电",
  "First hour 6, then 4/hour": "首小时 6 元，之后 4 元/小时",
  "12 flat rate": "夜间统一 12 元",
  "Base fee + 8": "基础费 + 8 元",
  "1.2/kWh": "1.2 元/千瓦时",
  "Cap 48": "封顶 48 元",
  "Monthly pass exempt": "月卡免收",
  "Queue weight +40": "队列权重 +40",
  "Auto release when full": "充满自动释放",
  Active: "启用",
  "All day": "全天",
  Whitelist: "白名单",
  Blacklist: "黑名单",
  Normal: "普通名单",
  Watchlist: "观察名单",
  "Monthly member": "月卡用户",
  "EV owner": "新能源车主",
  "Temporary visitor": "临时访客",
  "Payment exception": "支付异常",
  "Corporate account": "企业账户",
  "EV monthly member": "新能源月卡",
  "Reserved retrieval user": "预约取车用户",
  "Retail visitor": "散客访客",
  "Night-package member": "夜间套餐用户",
  "Repeated overtime exit": "多次超时离场",
  "Single order": "单次订单",
  "Manual review": "人工复核",
  "Auto pass": "自动放行",
  "Charging priority": "充电优先",
  "Supports contactless pay": "支持无接触支付",
  "Entry blocked": "禁止入场",
  "Peak-hour inbound priority": "高峰入场优先",
  "Charging fee discount": "充电费用优惠",
  "Supports advance outbound booking": "支持提前预约出场",
  "Self-service payment enabled": "已开通自助缴费",
  "Route release requires staff approval": "路线放行需人工确认",
  "Night cap applies automatically": "自动应用夜间封顶",
  "Invoice requested": "已申请发票",
  "Outbound confirmation required": "出场需确认",

  "Base parking": "基础停车费",
  "Peak shaping": "高峰调节费",
  "Fixed dispatch priority surcharge": "固定调度优先费",
  "1.20 CNY/kWh": "1.20 元/千瓦时",
  "Workday peak window": "工作日高峰时段",
  "Standard hourly window": "标准计时时段",
  "Zone A handoff": "A 区交接点",
  "Preview is generated from the persisted order, current dispatch priority, and live charger telemetry.":
    "费用预览来自持久化订单、当前调度优先级和实时充电桩遥测。",
  "Preview is generated from the order, dispatch priority, and live charger telemetry.":
    "费用预览来自订单、调度优先级和实时充电桩遥测。",

  "ALLOW_ENTRY_AND_CREATE_ORDER": "允许入场并创建订单",
  "ESTOP_AND_REVIEW": "触发急停并进入复核",
  "Person intrusion detected in transfer zone": "交接区检测到人员入侵",
  "AGV-04 battery below 20%": "AGV-04 电量低于 20%",
  "Secondary plate recognition mismatch": "二次车牌识别结果不一致",
  "Inbound barrier queue depth exceeded dispatch threshold": "入场道闸排队深度超过调度阈值",
  "EVSE-03 handshake retried after connector wake-up timeout": "EVSE-03 连接器唤醒超时后已重试握手",
  "North camera bitrate degraded below expected edge profile": "北侧摄像头码率低于预期边缘配置",
  "One finished order is pending settlement confirmation": "一笔已完成订单等待结算确认",
  "Manual review requested for abnormal slot release on A04": "A04 异常车位释放需要人工复核",
  "Emergency stop": "急停中",
  Processing: "处理中",
  "Pending review": "待复核",
  Open: "已开启",
  Resolved: "已恢复",
  Monitoring: "监控中",
  Escalated: "已升级",
  "South gate vision pre-processing node is healthy and forwarding OCR metadata": "南门视觉预处理节点运行正常，正在转发 OCR 元数据",
  "Barrier controller and AGV fleet gateway heartbeats are stable": "道闸控制器与 AGV 网关心跳稳定",
  "Operational cache and report fan-out are synchronized": "运营缓存与报表分发数据已同步",
  "Invoice and settlement projection jobs are completing on schedule": "发票与结算投影任务按计划完成",
  "Camera, gate, charger, and AGV telemetry simulation loops are healthy": "摄像头、闸机、充电桩与 AGV 遥测模拟循环正常",
  "South gate edge camera with OCR and handoff-zone intrusion ROI": "南门边缘摄像头，支持车牌 OCR 和交接区入侵检测",
  "Transfer-bay safety camera with person intrusion alarm": "交接区安全摄像头，支持人员入侵告警",
  "North ramp camera used for outbound queue observation and secondary plate read": "北侧坡道摄像头，用于出场队列观察和二次车牌识别",
  "Inbound barrier with loop detector and PLC relay control": "入场道闸，带地感线圈和 PLC 继电器控制",
  "Outbound handoff gate synchronized with AGV release window": "出场交接闸机，与 AGV 放行窗口同步",
  "Service corridor gate used for manual review and maintenance detours": "服务通道闸机，用于人工复核和维护绕行",
  "AC charger in premium bay C05": "C05 优先车位交流充电桩",
  "AC charger near handoff zone for short dwell sessions": "交接区附近交流充电桩，适合短停补能",
  "Fast-turnover charger waiting for connector lock confirmation": "快周转充电桩，等待连接器锁止确认",
  "Transfer-bay safety ROI cleared after pedestrian departure": "行人离开后，交接区安全 ROI 已清空",
  "Outbound gate is synchronized with the next handoff slot": "出场闸机已与下一个交接车位同步",
  "Connector EVSE-03 started an authorization handshake for SH-D3015": "EVSE-03 已为 SH-D3015 启动授权握手",
  "Inbound queue depth crossed the pre-dispatch planning threshold": "入场排队深度超过预调度规划阈值",
  "A short-lived pedestrian detection was logged outside the protected ROI": "受保护 ROI 外记录到一次短时行人识别",
  "Service corridor gate is idle and ready for exception routing": "服务通道闸机空闲，可用于异常路线",
  "One finished order is pending settlement callback confirmation": "一笔已完成订单等待结算回调确认",
  "Idle charger EVSE-02 sent a normal heartbeat frame": "空闲充电桩 EVSE-02 已发送正常心跳帧",
  "Bitrate dipped briefly below the preferred edge profile before recovery": "码率短暂低于首选边缘配置，随后恢复",
  "Outbound barrier confirmed a completed handoff release": "出场闸机已确认交接放行完成",
  "Connector lock on EVSE-03 retried once before engagement": "EVSE-03 连接器锁止重试一次后成功",
  "Manual-review transfer remains blocked until staff clearance": "人工复核转运在工作人员确认前保持拦截",
};

const phrasePatterns = [
  [/^(\d+)h ladder$/, (hours) => `${hours} 小时阶梯计费`],
  [/^([0-9.]+)x congestion multiplier$/, (rate) => `${rate} 倍拥堵调节`],
  [/^Carrying (.+)$/, (plate) => `搬运车辆 ${plate}`],
  [/^Relocating (.+) from (.+)$/, (plate, slot) => `将 ${plate} 从 ${slot} 移至缓冲区`],
  [/^VIP pickup for (.+)$/, (plate) => `VIP 优先取车 ${plate}`],
  [/^Storing (.+) into (.+)$/, (plate, slot) => `将 ${plate} 存入 ${slot}`],
  [/^Retrieving (.+)$/, (plate) => `取车 ${plate}`],
  [/^Handoff delivery for (.+)$/, (plate) => `交接区送车 ${plate}`],
  [/^Camera (.+) recognized plate (.+) with confidence (.+)$/, (camera, plate, confidence) => `${camera} 识别车牌 ${plate}，置信度 ${confidence}`],
  [/^Camera (.+) detected a safety intrusion and requested ESTOP$/, (camera) => `${camera} 检测到安全入侵并请求急停`],
  [/^(.+) queued for plate (.+)$/, (task, plate) => `${zhText(task)} 已为车辆 ${plate} 入队`],
  [/^Entry workflow created order (.+) for plate (.+)$/, (order, plate) => `入场流程已为车牌 ${plate} 创建订单 ${order}`],
  [/^Order (.+) was closed and the release gate was confirmed$/, (order) => `订单 ${order} 已关闭，出场闸机已确认放行`],
  [/^OCR recognized (.+) and forwarded metadata to the entry service$/, (plate) => `OCR 识别车牌 ${plate}，并已转发入场服务`],
  [/^Charging session for (.+) reached (.+) kWh$/, (plate, kwh) => `${plate} 的充电会话已达到 ${kwh} 千瓦时`],
  [/^(.+) accepted a loaded retrieval task for (.+)$/, (agv, plate) => `${agv} 已接收 ${plate} 的载车取车任务`],
  [/^North ramp camera confirmed outbound plate (.+)$/, (plate) => `北侧坡道摄像头确认出场车牌 ${plate}`],
  [/^VIP retrieval for (.+) was inserted at the head of the queue$/, (plate) => `${plate} 的 VIP 取车任务已插入队首`],
  [/^Order (.+) is waiting for manual release approval$/, (order) => `订单 ${order} 正等待人工放行审批`],
  [/^Delivered energy increased by (.+) kWh during the active session$/, (kwh) => `当前充电会话电量增加 ${kwh} 千瓦时`],
  [/^Forecast-driven relocation task queued for (.+)$/, (plate) => `预测驱动的移位任务已为 ${plate} 入队`],
  [/^AGV-(.+) entered charging standby below the configured battery threshold$/, (id) => `AGV-${id} 电量低于阈值，已进入充电待命`],
  [/^AGV-(.+) started pre-dispatch relocation from a deep-slot aisle$/, (id) => `AGV-${id} 已从深层车道启动预调度移位`],
  [/^AGV-(.+) completed a perimeter patrol cycle near Zone A$/, (id) => `AGV-${id} 已完成 A 区周界巡检`],
  [/^Fallback state synced for (.+)$/, (plate) => `本地兜底状态已同步：${plate}`],
];

export function zhText(value, fallback = "暂无") {
  if (value === undefined || value === null || value === "") return fallback;
  const text = String(value);
  if (dictionary[text]) return dictionary[text];

  for (const [pattern, formatter] of phrasePatterns) {
    const match = text.match(pattern);
    if (match) return formatter(...match.slice(1));
  }

  return text.replace(/\bCNY\b/g, "￥");
}

export function zhMoney(value) {
  if (value === undefined || value === null || value === "") return "￥0.00";
  const numeric = Number(String(value).replace(/[^\d.-]/g, ""));
  if (Number.isFinite(numeric)) return `￥${numeric.toFixed(2)}`;
  return zhText(value).replace(/\bCNY\b/g, "￥");
}

export function zhList(values) {
  return values.map((value) => zhText(value));
}
